Chaning to F15 before figuring out CentOS6 dependencies ..
Need Pulp etc ..

[katello]
[katello] err: /Stage[main]//Node[katello]/Package[katello-all]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install katello-all' returned 1: Error: Package: katello-cli-common-0.1.10-1.git.922.f2329b3.el6.noarch (epel-katello)
           Requires: python-kerberos
Error: Package: katello-all-0.1.96-1.git.133.5a44f75.el6.x86_64 (epel-katello)
           Requires: pulp
Error: Package: katello-all-0.1.96-1.git.133.5a44f75.el6.x86_64 (epel-katello)
           Requires: candlepin-tomcat6
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest